// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPxu2ricVJAIkPnpJl-CgmmacmLUq7InQ',
    appId: '1:859479165490:web:e42ba349da2070292aca2b',
    messagingSenderId: '859479165490',
    projectId: 'fir-practicetechbrothers',
    authDomain: 'fir-practicetechbrothers.firebaseapp.com',
    storageBucket: 'fir-practicetechbrothers.firebasestorage.app',
    measurementId: 'G-6X6WJ4BB73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vrI7GES9dtio9H6hJWl6BtQAn96s76k',
    appId: '1:859479165490:android:1e356454611a5c712aca2b',
    messagingSenderId: '859479165490',
    projectId: 'fir-practicetechbrothers',
    storageBucket: 'fir-practicetechbrothers.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD6sFmXadjJ6dyHM9A-ohS2j1eKe0lk9d0',
    appId: '1:859479165490:ios:02f57f8e752c76052aca2b',
    messagingSenderId: '859479165490',
    projectId: 'fir-practicetechbrothers',
    storageBucket: 'fir-practicetechbrothers.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebasePracticeThetechbrothers',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD6sFmXadjJ6dyHM9A-ohS2j1eKe0lk9d0',
    appId: '1:859479165490:ios:02f57f8e752c76052aca2b',
    messagingSenderId: '859479165490',
    projectId: 'fir-practicetechbrothers',
    storageBucket: 'fir-practicetechbrothers.firebasestorage.app',
    iosBundleId: 'com.example.flutterFirebasePracticeThetechbrothers',
  );
}
